### ISSUE TITLE
Illegal State Exception thrown in Android OS 10

### ISSUE THREAD

**Issue by shakunthalakrishnamurthy** [OpenSooq/Gligar#12]
IllegalStateException is thrown when the user picks the images from the library's gallery

Fatal Exception: java.lang.IllegalStateException: albumCursor.getString(al…dex(DISPLAY_NAME_COLUMN)) must not be null
       at com.opensooq.supernova.gligar.dataSource.ImagesDataSource$loadAlbums$1.invoke(ImagesDataSource.java:40)
       at com.opensooq.supernova.gligar.dataSource.ImagesDataSource$loadAlbums$1.invoke(ImagesDataSource.java:22)
       at com.opensooq.supernova.gligar.utils.ExtKt.doWhile(ExtKt.java:26)
       at com.opensooq.supernova.gligar.dataSource.ImagesDataSource.loadAlbums(ImagesDataSource.java:38)
       at com.opensooq.supernova.gligar.ui.PickerViewModel$getAlbums$2.invokeSuspend(PickerViewModel.java:104)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:241)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.java:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:740)

**Comment by shakunthalakrishnamurthy** [comment]
Sorry, I had the old version of your library. Working fine with v1.1.0. Thanks
