### ISSUE TITLE
Unable to start Gligar activity

### ISSUE THREAD

**Issue by MKickelberg** [OpenSooq/Gligar#14]
Starting the image picker crashes on some devices sometimes. I dont know why. Any idea what the following is about:

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{rstls.pdfbook/com.opensooq.supernova.gligar.ui.ImagePickerActivity}: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

AND

Caused by java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
       at com.opensooq.supernova.gligar.ui.PickerViewModel.loadSaveState$gligar_release(PickerViewModel.java:205)
       at com.opensooq.supernova.gligar.ui.ImagePickerActivity.onCreate(ImagePickerActivity.java:118)
       at android.app.Activity.performCreate(Activity.java:7955)
       at android.app.Activity.performCreate(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

This never happened on my test devices so I cannot give any more details. But this seems to constantly happen to about 2% of my users.

I am a beginner so this might be due to some fault of mine? I am confused because this happens only "sometimes" to "some users". Do I have to declare this activity in the AndroidManifest even if its imported or how does this work.

**Comment by hani-momanii** [comment]
@MKickelberg  can you provide the device model and android version?

**Comment by dastan1302** [comment]
@hani-momanii We also having this issue 
![image](https://user-images.githubusercontent.com/9525482/91935690-12ddb200-ed10-11ea-9623-3b3bf935f5e5.png)
![image](https://user-images.githubusercontent.com/9525482/91935711-2557eb80-ed10-11ea-958c-3ac5acdf0b6f.png)

Because we using "com.nbsp:materialfilepicker:1.9.1" from https://github.com/nbsp-team/MaterialFilePicker, which as found uses your library internally and causes crash
