### ISSUE TITLE
[CRASH on Android Q] When media files in Internal storage

### ISSUE THREAD

**Issue by monsterbrain** [OpenSooq/Gligar#3]
When there exists images in the root folder of the internal storage, the library crashes on start. (some kind of null exception). When the images are removed, it works fine. Occurred in pIxel 3 device.

**Comment by hani-momanii** [comment]
@monsterbrain Can you add the crash stack trace?

**Comment by monsterbrain** [comment]
Sorry for the late reply ...

java.lang.IllegalStateException: albumCursor.getString(al…dex(DISPLAY_NAME_COLUMN)) must not be null
        at com.opensooq.supernova.gligar.dataSource.ImagesDataSource$loadAlbums$1.invoke(ImagesDataSource.kt:40)
        at com.opensooq.supernova.gligar.dataSource.ImagesDataSource$loadAlbums$1.invoke(ImagesDataSource.kt:22)
        at com.opensooq.supernova.gligar.utils.ExtKt.doWhile(Ext.kt:26)
        at com.opensooq.supernova.gligar.dataSource.ImagesDataSource.loadAlbums(ImagesDataSource.kt:38)
        at com.opensooq.supernova.gligar.ui.PickerViewModel$getAlbums$2.invokeSuspend(PickerViewModel.kt:104)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by deepaktundwal** [comment]
I am also facing the issue in Android Q. @monsterbrain @monsterbrain any solution for this issue?

**Comment by monsterbrain** [comment]
@deepaktundwal : One thing to solve it is to just do a null check for the album title reading DISPLAY_NAME_COLUMN query..

**Comment by hani-momanii** [comment]
[Fixed on v1.1.0.](https://github.com/OpenSooq/Gligar/releases/tag/v1.1.0)
