### ISSUE TITLE
Crash on android 12

### ISSUE THREAD

**Issue by AmrAhmed109** [OpenSooq/Gligar#31]
2022-04-30 15:10:01.343 21348-21348/com.example.imagepicker E/ThemeUtils: View class androidx.appcompat.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2022-04-30 15:10:01.350 21348-21348/com.example.imagepicker E/ThemeUtils: View class androidx.appcompat.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
2022-04-30 15:10:01.368 21348-21348/com.example.imagepicker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.imagepicker, PID: 21348
    java.lang.IllegalArgumentException: Invalid token LIMIT
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
        at android.content.ContentResolver.query(ContentResolver.java:1226)
        at android.content.ContentResolver.query(ContentResolver.java:1158)
        at android.content.ContentResolver.query(ContentResolver.java:1114)
        at com.opensooq.supernova.gligar.dataSource.ImagesDataSource.loadAlbumImages(ImagesDataSource.kt:64)
        at com.opensooq.supernova.gligar.ui.PickerViewModel$getImages$2.invokeSuspend(PickerViewModel.kt:99)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by tauseeqafzal** [comment]
Issue Resolved or Not?
